from typing import Any, Iterable, Iterator, Optional, TextIO

class jsonlines:
    class Reader:
        def __init__(self, iterable: Iterable[Any], **kwargs: Any) -> None: ...
        def iter(
            self,
            type: Optional[Any] = None,
            skip_invalid: bool = False,
            skip_empty: bool = False,
        ) -> Iterator[Any]: ...
        def read(
            self,
            type: Optional[Any] = None,
            skip_invalid: bool = False,
            skip_empty: bool = False,
        ) -> Any: ...
        def close(self) -> None: ...

    class Writer:
        def __init__(self, writable: TextIO, **kwargs: Any) -> None: ...
        def write(self, obj: Any) -> None: ...
        def close(self) -> None: ...

def open(filename: str, mode: str = "r", **kwargs: Any) -> Any: ...
