"""
DPO Training Script for Sotopia

This script trains a policy model using Direct Preference Optimization (DPO)
on preference pairs generated by the reward model.
"""
import argparse

from accelerate import Accelerator

from sotopia_rl import SotopiaDPOTrainer


def parse_args():
    parser = argparse.ArgumentParser(description="Train DPO model on preference pairs")
    
    # Model arguments
    parser.add_argument(
        "--model_name",
        type=str,
        default="Qwen/Qwen2.5-7B-Instruct",
        help="HuggingFace model name or path"
    )
    parser.add_argument(
        "--policy_adapter_path",
        type=str,
        default=None,
        help="Path to pre-trained policy adapter (optional)"
    )
    parser.add_argument(
        "--ref_adapter_path",
        type=str,
        default=None,
        help="Path to reference model adapter (optional, auto-created if None)"
    )
    
    # Data arguments
    parser.add_argument(
        "--dpo_data_path",
        type=str,
        default="data/dpo_pairs_scored.json",
        help="Path to DPO training data (output from score_dpo_pairs.py)"
    )
    parser.add_argument(
        "--template_path",
        type=str,
        default="evals/qwen2.5-7b.jinja",
        help="Path to Jinja chat template"
    )
    parser.add_argument(
        "--val_ratio",
        type=float,
        default=0.05,
        help="Validation set ratio"
    )
    
    # Training arguments
    parser.add_argument(
        "--output_dir",
        type=str,
        default="saves/dpo_checkpoint",
        help="Output directory for checkpoints"
    )
    parser.add_argument(
        "--per_device_train_batch_size",
        type=int,
        default=2,
        help="Training batch size per device"
    )
    parser.add_argument(
        "--per_device_eval_batch_size",
        type=int,
        default=2,
        help="Evaluation batch size per device"
    )
    parser.add_argument(
        "--gradient_accumulation_steps",
        type=int,
        default=4,
        help="Gradient accumulation steps"
    )
    parser.add_argument(
        "--num_train_epochs",
        type=int,
        default=3,
        help="Number of training epochs"
    )
    parser.add_argument(
        "--learning_rate",
        type=float,
        default=5e-6,
        help="Learning rate"
    )
    parser.add_argument(
        "--beta",
        type=float,
        default=0.1,
        help="DPO beta parameter (temperature for preference learning)"
    )
    parser.add_argument(
        "--max_length",
        type=int,
        default=4096,
        help="Maximum sequence length"
    )
    parser.add_argument(
        "--max_prompt_length",
        type=int,
        default=2048,
        help="Maximum prompt length"
    )
    parser.add_argument(
        "--save_steps",
        type=int,
        default=100,
        help="Save checkpoint every N steps"
    )
    
    # LoRA arguments
    parser.add_argument(
        "--use_lora",
        action="store_true",
        help="Use LoRA for efficient fine-tuning"
    )
    parser.add_argument(
        "--lora_r",
        type=int,
        default=8,
        help="LoRA rank"
    )
    parser.add_argument(
        "--lora_alpha",
        type=int,
        default=32,
        help="LoRA alpha"
    )
    parser.add_argument(
        "--lora_dropout",
        type=float,
        default=0.1,
        help="LoRA dropout"
    )
    parser.add_argument(
        "--target_modules",
        type=str,
        default="q_proj,v_proj",
        help="Comma-separated list of target modules for LoRA"
    )
    
    # Logging arguments
    parser.add_argument(
        "--wandb_project",
        type=str,
        default="sotopia-dpo",
        help="Weights & Biases project name"
    )
    parser.add_argument(
        "--wandb_run_name",
        type=str,
        default="dpo-run",
        help="Weights & Biases run name"
    )
    
    return parser.parse_args()


def main():
    args = parse_args()
    
    # Initialize accelerator
    accelerator = Accelerator()
    
    if accelerator.is_main_process:
        print("=" * 60)
        print("DPO Training Configuration")
        print("=" * 60)
        for key, value in vars(args).items():
            print(f"  {key}: {value}")
        print("=" * 60)
    
    # Initialize and run trainer
    trainer = SotopiaDPOTrainer(args, accelerator)
    trainer.train()
    
    if accelerator.is_main_process:
        print("DPO training complete!")


if __name__ == "__main__":
    main()

